const BMSS = {
  master_denomination: {
    tablename: 'master_denomination',
    prefix_: 'md_',
    prefix: 'md',
    insertColumns: ['code', 'description', 'value', 'status', 'create_by', 'create_date'],
    selectColumns: [
      'md_id',
      'md_code',
      'md_description',
      'md_value',
      'md_status',
      'md_create_by',
      'md_create_date',
    ],
    selectOptionsColumns: {
      id: 'md_id',
      code: 'md_code',
      description: 'md_description',
      value: 'md_value',
      status: 'md_status',
      create_by: 'md_create_by',
      create_date: 'md_create_date',
    },
    columns: {
      id: 'id',
      code: 'code',
      description: 'description',
      value: 'value',
      status: 'status',
      create_by: 'create_by',
      create_date: 'create_date',
    },
  },
  cashdrawer_cash_float: {
    tablename: 'cashdrawer_cash_float',
    prefix_: 'ccf_',
    prefix: 'ccf',
    insertColumns: ['date', 'branch_id', 'pos', 'shift', 'cashier', 'cash_float', 'denomination'],
    selectColumns: [
      'ccf_id',
      'ccf_date',
      'ccf_branch_id',
      'ccf_pos',
      'ccf_shift',
      'ccf_cashier',
      'ccf_cash_float',
      'ccf_denomination',
    ],
    selectOptionsColumns: {
      id: 'ccf_id',
      date: 'ccf_date',
      branch_id: 'ccf_branch_id',
      pos: 'ccf_pos',
      shift: 'ccf_shift',
      cashier: 'ccf_cashier',
      cash_float: 'ccf_cash_float',
      denomination: 'ccf_denomination',
    },
  },
  cashdrawer_report: {
    tablename: 'cashdrawer_report',
    prefix_: 'cr_',
    prefix: 'cr',
    insertColumns: ['branch_id', 'shift', 'date', 'pos_id', 'user_id', 'total', 'denomination'],
    selectColumns: [
      'cr_id',
      'cr_branch_id',
      'cr_shift',
      'cr_date',
      'cr_pos_id',
      'cr_user_id',
      'cr_total',
      'cr_denomination',
    ],
    selectOptionsColumns: {
      id: 'cr_id',
      branch_id: 'cr_branch_id',
      shift: 'cr_shift',
      date: 'cr_date',
      pos_id: 'cr_pos_id',
      user_id: 'cr_user_id',
      total: 'cr_total',
      denomination: 'cr_denomination',
    },
  },
  cashdrawer_activity: {
    tablename: 'cashdrawer_activity',
    prefix: 'ca',
    prefix_: 'ca_',
    insertColumns: [
      'branch_id',
      'shift_number',
      'pos_id',
      'shift_date',
      'user_id',
      'datetime',
      'description',
      'status',
    ],
    selectColumns: [
      'ca_id',
      'ca_branch_id',
      'ca_shift_number',
      'ca_pos_id',
      'ca_shift_date',
      'ca_user_id',
      'ca_datetime',
      'ca_description',
      'ca_status',
    ],
    selectOptionsColumns: {
      id: 'ca_id',
      branch_id: 'ca_branch_id',
      shift_number: 'ca_shift_number',
      pos_id: 'ca_pos_id',
      shift_date: 'ca_shift_date',
      user_id: 'ca_user_id',
      datetime: 'ca_datetime',
      description: 'ca_description',
      status: 'ca_status',
    },
  },
  cash_drop: {
    tablename: 'cash_drop',
    prefix_: 'cd_',
    prefix: 'cd',
    insertColumns: [
      'branch_id',
      'shift_number',
      'shift_date',
      'pos_id',
      'user_id',
      'datetime',
      'amount',
    ],
    selectColumns: [
      'cd_id',
      'cd_branch_id',
      'cd_shift_number',
      'cd_shift_date',
      'cd_pos_id',
      'cd_user_id',
      'cd_datetime',
      'cd_amount',
    ],
    selectOptionsColumns: {
      id: 'cd_id',
      branch_id: 'cd_branch_id',
      shift_number: 'cd_shift_number',
      shift_date: 'cd_shift_date',
      pos_id: 'cd_pos_id',
      user_id: 'cd_user_id',
      datetime: 'cd_datetime',
      amount: 'cd_amount',
    },
  },
  change_activity: {
    tablename: 'change_activity',
    prefix: 'ca_',
    insertColumns: ['ca_detail_id', 'cd_total_amount', 'cd_cash_tender', 'cd_change'],
    selectColumns: ['ca_id', 'ca_detail_id', 'ca_total_amount', 'ca_cash_tender', 'ca_change'],
    selectOptionsColumns: {
      id: 'ca_id',
      detail_id: 'ca_detail_id',
      total_amount: 'ca_total_amount',
      cash_tender: 'ca_cash_tender',
      change: 'ca_change',
    },
  },
  system_logs: {
    tablename: 'system_logs',
    prefix_: 'sl_',
    prefix: 'sl',
    insertColumns: ['logdate', 'loglevel', 'source', 'message', 'userid', 'ipaddress'],
    selectColumns: [
      'sl_logid',
      'sl_logdate',
      'sl_loglevel',
      'sl_source',
      'sl_message',
      'sl_userid',
      'sl_ipaddress',
    ],
    selectOptionsColumns: {
      logid: 'sl_logid',
      logdate: 'sl_logdate',
      loglevel: 'sl_loglevel',
      source: 'sl_source',
      message: 'sl_message',
      userid: 'sl_userid',
      ipaddress: 'sl_ipaddress',
    },
  },
}

exports.BMSS = BMSS
