const BMSS = {
  master_denomination: {
    tablename: 'master_denomination',
    prefix_: 'md_',
    prefix: 'md',
    insertColumns: ['code', 'description', 'value', 'status', 'create_by', 'create_date'],
    selectColumns: [
      'md_id',
      'md_code',
      'md_description',
      'md_value',
      'md_status',
      'md_create_by',
      'md_create_date',
    ],
    selectOptionsColumns: {
      id: 'md_id',
      code: 'md_code',
      description: 'md_description',
      value: 'md_value',
      status: 'md_status',
      create_by: 'md_create_by',
      create_date: 'md_create_date',
    },
    columns: {
      id: 'id',
      code: 'code',
      description: 'description',
      value: 'value',
      status: 'status',
      create_by: 'create_by',
      create_date: 'create_date',
    },
  },
  cashdrawer_cash_float: {
    tablename: 'cashdrawer_cash_float',
    prefix: 'ccf_',
    insertColumns: [
      'ccf_date',
      'ccf_pos',
      'ccf_shift',
      'ccf_cashier',
      'ccf_cash_float',
      'ccf_denomination',
    ],
    selectColumns: [
      'ccf_id',
      'ccf_date',
      'ccf_pos',
      'ccf_shift',
      'ccf_cashier',
      'ccf_cash_float',
      'ccf_denomination',
    ],
    selectOptionsColumns: {
      id: 'ccf_id',
      date: 'ccf_date',
      pos: 'ccf_pos',
      shift: 'ccf_shift',
      cashier: 'ccf_cashier',
      cash_float: 'ccf_cash_float',
      denomination: 'ccf_denomination',
    },
  },
  cashdrawer_report: {
    tablename: 'cashdrawer_report',
    prefix: 'cr_',
    insertColumns: ['  cr_cash_float_id', 'cr_total', 'cr_denomination'],
    selectColumns: ['cr_id', 'cr_cash_float_id', 'cr_total', 'cr_denomination'],
    selectOptionsColumns: {
      id: 'cr_id',
      cash_float_id: 'cr_cash_float_id',
      total: 'cr_total',
      denomination: 'cr_denomination',
    },
  },
  cashdrawer_activity: {
    tablename: 'cashdrawer_activity',
    prefix: 'ca_',
    insertColumns: [
      'ca_shift_number',
      'ca_pos_id',
      'ca_shift_date',
      'ca_user_id',
      'ca_datetime',
      'ca_description',
      'ca_status',
    ],
    selectColumns: [
      'ca_id',
      'ca_shift_number',
      'ca_pos_id',
      'ca_shift_date',
      'ca_user_id',
      'ca_datetime',
      'ca_description',
      'ca_status',
    ],
    selectOptionsColumns: {
      id: 'ca_id',
      shift_number: 'ca_shift_number',
      pos_id: 'ca_pos_id',
      shift_date: 'ca_shift_date',
      user_id: 'ca_user_id',
      datetime: 'ca_datetime',
      description: 'ca_description',
      status: 'ca_status',
    },
  },
  cash_drop: {
    tablename: 'cash_drop',
    prefix: 'cd_',
    insertColumns: [
      'cd_shift_number',
      'cd_shift_date',
      'cd_pos_id',
      'cd_user_id',
      'cd_datetime',
      'cd_amount',
    ],
    selectColumns: [
      'cd_id',
      'cd_shift_number',
      'cd_shift_date',
      'cd_pos_id',
      'cd_user_id',
      'cd_datetime',
      'cd_amount',
    ],
    selectOptionsColumns: {
      id: 'cd_id',
      shift_number: 'cd_shift_number',
      shift_date: 'cd_shift_date',
      pos_id: 'cd_pos_id',
      user_id: 'cd_user_id',
      datetime: 'cd_datetime',
      amount: 'cd_amount',
    },
  },
  change_activity: {
    tablename: 'change_activity',
    prefix: 'ca_',
    insertColumns: ['ca_detail_id', 'cd_total_amount', 'cd_cash_tender', 'cd_change'],
    selectColumns: ['ca_id', 'ca_detail_id', 'ca_total_amount', 'ca_cash_tender', 'ca_change'],
    selectOptionsColumns: {
      id: 'ca_id',
      detail_id: 'ca_detail_id',
      total_amount: 'ca_total_amount',
      cash_tender: 'ca_cash_tender',
      change: 'ca_change',
    },
  },
}

exports.BMSS = BMSS
