const Inventory = {
  inventory_count: {
    tablename: 'inventory_count',
    prefix: 'ic',
    prefix_: 'ic_',
    selectColums: [
      `ic_countid`,
      `ic_count_date`,
      `ic_locationid`,
      `ic_countby`,
      `ic_countverification`,
      `ic_notes`,
    ],
    insertColumns: [`count_date`, `locationid`, `countby`, `countverification`, `notes`],
    selectOptionColumn: {
      countid: 'ic_countid',
      count_date: 'ic_count_date',
      locationid: 'ic_locationid',
      countby: 'ic_countby',
      countverification: 'ic_countverification',
      notes: 'ic_notes',
    },
  },
  inventory_history: {
    tablename: 'inventory_history',
    prefix: 'ih',
    prefix_: 'ih_',
    selectColums: [
      `ih_historyid`,
      `ih_productid`,
      `ih_quantity`,
      `ih_type`,
      `ih_createddate`,
      `ih_createdby`,
    ],
    insertColumns: [`productid`, `quantity`, `type`, `createddate`, `createdby`],
    selectOptionColumn: {
      historyid: 'ih_historyid',
      productid: 'ih_productid',
      quantity: 'ih_quantity',
      type: 'ih_type',
      createddate: 'ih_createddate',
      createdby: 'ih_createdby',
    },
  },
  inventory_valuation_items: {
    tablename: 'inventory_valuation_items',
    prefix: 'ivi',
    prefix_: 'ivi_',
    selectColums: [
      `ivi_itemid`,
      `ivi_reportid`,
      `ivi_productid`,
      `ivi_quantity`,
      `ivi_unitcost`,
      `ivi_totalvalue`,
      `ivi_branchid`,
      `ivi_category`,
      `ivi_productname`,
    ],
    insertColumns: [
      `itemid`,
      `reportid`,
      `productid`,
      `quantity`,
      `unitcost`,
      `totalvalue`,
      `branchid`,
      `category`,
      `productname`,
    ],
    selectOptionColumn: {
      itemid: 'ivi_itemid',
      reportid: 'ivi_reportid',
      productid: 'ivi_productid',
      quantity: 'ivi_quantity',
      unitcost: 'ivi_unitcost',
      totalvalue: 'ivi_totalvalue',
      branchid: 'ivi_branchid',
      category: 'ivi_category',
      productname: 'ivi_productname',
    },
  },
  inventory_valuation_report: {
    tablename: 'inventory_valuation_report',
    prefix: 'ivr',
    prefix_: 'ivr_',
    selectColums: [`ivr_reportid`, `ivr_reportdate`, `ivr_generateby`, `ivr_notes`],
    insertColumns: [`reportdate`, `generateby`, `notes`],
    selectOptionColumn: {
      reportid: 'ivr_reportid',
      reportdate: 'ivr_reportdate',
      generateby: 'ivr_generateby',
      notes: 'ivr_notes',
    },
  },
}

exports.Inventory = Inventory
