const Masters = {
  master_access_type: {
    tablename: 'master_access_type',
    prefix: 'map',
    prefix_: 'map_',
    selectColums: [
      `mat_accesscode`,
      `mat_accessname`,
      `mat_status`,
      `mat_createdby`,
      `mat_createddate`,
    ],
    insertColumns: [`accessname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      accesscode: 'mat_accesscode',
      accessname: 'mat_accessname',
      status: 'mat_status',
      createdby: 'mat_createdby',
      createddate: 'mat_createddate',
    },
  },
  master_branch: {
    tablename: 'master_branch',
    prefix: 'mb',
    prefix_: 'mb_',
    selectColums: [
      `mb_branchid`,
      `mb_branchname`,
      `mb_tin`,
      `mb_address`,
      `mb_logo`,
      `mb_status`,
      `mb_createdby`,
      `mb_createddate`,
    ],
    insertColumns: [
      'branchid',
      `branchname`,
      `tin`,
      `address`,
      `logo`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      branchid: 'mb_branchid',
      branchname: 'mb_branchname',
      tin: 'mb_tin',
      address: 'mb_address',
      logo: 'mb_logo',
      status: 'mb_status',
      createdby: 'mb_createdby',
      createddate: 'mb_createddate',
    },
  },
  master_category: {
    tablename: 'master_category',
    prefix: 'mc',
    prefix_: 'mc_',
    selectColums: [
      `mc_categorycode`,
      `mc_categoryname`,
      `mc_status`,
      `mc_createdby`,
      `mc_createddate`,
    ],
    insertColumns: [`categoryname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      categorycode: 'mc_categorycode',
      categoryname: 'mc_categoryname',
      status: 'mc_status',
      createdby: 'mc_createdby',
      createddate: 'mc_createddate',
    },
  },
  master_denomination: {
    tablename: 'master_denomination',
    prefix: 'md',
    prefix_: 'md_',
    selectColums: [
      `mc_categorycode`,
      `mc_categoryname`,
      `mc_status`,
      `mc_createdby`,
      `mc_createddate`,
    ],
    insertColumns: [`categoryname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      categorycode: 'mc_categorycode',
      categoryname: 'mc_categoryname',
      status: 'mc_status',
      createdby: 'mc_createdby',
      createddate: 'mc_createddate',
    },
  },
  master_employee: {
    tablename: 'master_employee',
    prefix: 'me',
    prefix_: 'me_',
    selectColums: [
      `me_employeeid`,
      `me_fullname`,
      `me_position`,
      `me_contactinfo`,
      `me_datehired`,
      `me_status`,
      `me_createdby`,
      `me_createddate`,
    ],
    insertColumns: [
      `employeeid`,
      `fullname`,
      `position`,
      `contactinfo`,
      `datehired`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      employeeid: 'me_employeeid',
      fullname: 'me_fullname',
      position: 'me_position',
      contactinfo: 'me_contactinfo',
      datehired: 'me_datehired',
      status: 'me_status',
      createdby: 'me_createdby',
      createddate: 'me_createddate',
    },
  },
  master_location: {
    tablename: 'master_location',
    prefix: 'ml',
    prefix_: 'ml_',
    selectColums: [
      `ml_locationid`,
      `ml_locationname`,
      `ml_status`,
      `ml_createdby`,
      `ml_createddate`,
    ],
    insertColumns: [`locationname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      locationid: 'ml_locationid',
      locationname: 'ml_locationname',
      status: 'ml_status',
      createdby: 'ml_createdby',
      createddate: 'ml_createddate',
    },
  },
  master_material_cost: {
    tablename: 'master_material_cost',
    prefix: 'mmc',
    prefix_: 'mmc_',
    selectColums: [
      `mmc_materialid`,
      `mmc_materialname`,
      `mmc_unitcost`,
      `mmc_unit`,
      `mmc_status`,
      `mmc_createdby`,
      `mmc_createddate`,
    ],
    insertColumns: [`materialname`, `unitcost`, `unit`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      materialid: 'mmc_materialid',
      materialname: 'mmc_materialname',
      unitcost: 'mmc_unitcost',
      unit: 'mmc_unit',
      status: 'mmc_status',
      createdby: 'mmc_createdby',
      createddate: 'mmc_createddate',
    },
  },
  master_payment: {
    tablename: 'master_payment',
    prefix: 'mp',
    prefix_: 'mp_',
    selectColums: [`mp_paymentid`, `mp_paymentname`, `mp_status`, `mp_createdby`, `mp_createddate`],
    insertColumns: [`paymentname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      paymentid: 'mp_paymentid',
      paymentname: 'mp_paymentname',
      status: 'mp_status',
      createdby: 'mp_createdby',
      createddate: 'mp_createddate',
    },
  },
  master_pos: {
    tablename: 'master_pos',
    prefix: 'mp',
    prefix_: 'mp_',
    selectColums: [
      `mp_posid`,
      `mp_posname`,
      `mp_serial`,
      `mp_min`,
      `mp_ptu`,
      `mp_status`,
      `mp_createdby`,
      `mp_createddate`,
    ],
    insertColumns: [`posname`, `serial`, `min`, `ptu`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      posid: 'mp_posid',
      posname: 'mp_posname',
      serial: 'mp_serial',
      min: 'mp_min',
      ptu: 'mp_ptu',
      status: 'mp_status',
      createdby: 'mp_createdby',
      createddate: 'mp_createddate',
    },
  },
  master_position_type: {
    tablename: 'master_position_type',
    prefix: 'mpt',
    prefix_: 'mpt_',
    selectColums: [
      `mpt_positioncode`,
      `mpt_positionname`,
      `mpt_status`,
      `mpt_createdby`,
      `mpt_createddate`,
    ],
    insertColumns: [`positionname`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      positioncode: 'mpt_positioncode',
      positionname: 'mpt_positionname',
      status: 'mpt_status',
      createdby: 'mpt_createdby',
      createddate: 'mpt_createddate',
    },
  },
  master_product: {
    tablename: 'master_product',
    prefix: 'mp',
    prefix_: 'mp_',
    selectColums: [
      `mp_productid`,
      `mp_description`,
      `mp_price`,
      `mp_category`,
      `mp_barcode`,
      `mp_productimage`,
      `mp_status`,
      `mp_createdby`,
      `mp_createddate`,
      `mp_cost`,
    ],
    insertColumns: [
      `description`,
      `price`,
      `category`,
      `barcode`,
      `productimage`,
      `status`,
      `createdby`,
      `createddate`,
      `cost`,
    ],
    selectOptionColumn: {
      productid: 'mp_productid',
      description: 'mp_description',
      price: 'mp_price',
      category: 'mp_category',
      barcode: 'mp_barcode',
      productimage: 'mp_productimage',
      status: 'mp_status',
      createdby: 'mp_createdby',
      createddate: 'mp_createddate',
      cost: 'mp_cost',
    },
  },
  master_user: {
    tablename: 'master_user',
    prefix: 'mu',
    prefix_: 'mu_',
    selectColums: [
      `mu_usercode`,
      `mu_employeeid`,
      `mu_accesstype`,
      `mu_status`,
      `mu_username`,
      `mu_password`,
      `mu_branchid`,
      `mu_createdby`,
      `mu_createddate`,
    ],
    insertColumns: [
      `employeeid`,
      `accesstype`,
      `status`,
      `username`,
      `password`,
      `branchid`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      usercode: 'mu_usercode',
      employeeid: 'mu_employeeid',
      accesstype: 'mu_accesstype',
      status: 'mu_status',
      username: 'mu_username',
      password: 'mu_password',
      branchid: 'mu_branchid',
      createdby: 'mu_createdby',
      createddate: 'mu_createddate',
    },
  },

  master_vendor: {
    tablename: 'master_vendor',
    prefix: 'mv',
    prefix_: 'mv_',
    selectColums: [
      `mv_vendorid`,
      `mv_vendorname`,
      `mv_contactname`,
      `mv_contactemail`,
      `mv_contactphone`,
      `mv_address`,
      `mv_status`,
      `mv_createdby`,
      `mv_createddate`,
    ],
    insertColumns: [
      `vendorname`,
      `contactname`,
      `contactemail`,
      `contactphone`,
      `address`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      vendorid: 'mv_vendorid',
      vendorname: 'mv_vendorname',
      contactname: 'mv_contactname',
      contactemail: 'mv_contactemail',
      contactphone: 'mv_contactphone',
      address: 'mv_address',
      status: 'mv_status',
      createdby: 'mv_createdby',
      createddate: 'mv_createddate',
    },
  },
}

exports.Masters = Masters
