const Product = {
  product_component: {
    tablename: 'product_component',
    prefix: 'pc',
    prefix_: 'pc_',
    selectColums: [
      `pc_componentid`,
      `pc_productid`,
      `pc_components`,
      `pc_status`,
      `pc_createdby`,
      `pc_createddate`,
    ],
    insertColumns: [`productid`, `components`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      componentid: 'pc_componentid',
      productid: 'pc_productid',
      components: 'pc_components',
      status: 'pc_status',
      createdby: 'pc_createdby',
      createddate: 'pc_createddate',
    },
  },
  product_inventory: {
    tablename: 'product_inventory',
    prefix: 'pi',
    prefix_: 'pi_',
    selectColums: [`pi_inventoryid`, `pi_productid`, `pi_branchid`, `pi_quantity`, `pi_category`],
    insertColumns: [`productid`, `branchid`, `quantity`, `category`],
    selectOptionColumn: {
      inventoryid: 'pi_inventoryid',
      productid: 'pi_productid',
      branchid: 'pi_branchid',
      quantity: 'pi_quantity',
      category: 'pi_category',
    },
  },
  product_price: {
    tablename: 'product_price',
    prefix: 'pp',
    prefix_: 'pp_',
    selectColums: [
      `pp_product_price_id`,
      `pp_product_id`,
      `pp_description`,
      `pp_barcode`,
      `pp_product_image`,
      `pp_price`,
      `pp_category`,
      `pp_previous_price`,
      `pp_price_change`,
      `pp_price_change_date`,
      `pp_status`,
      `pp_createdby`,
      `pp_createddate`,
    ],
    insertColumns: [
      `product_id`,
      `description`,
      `barcode`,
      `productimage`,
      `price`,
      `category`,
      `previous_price`,
      `price_change`,
      `price_change_date`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      product_price_id: 'pp_product_price_id',
      product_id: 'pp_product_id',
      description: 'pp_description',
      barcode: 'pp_barcode',
      productimage: 'pp_product_image',
      price: 'pp_price',
      category: 'pp_category',
      previous_price: 'pp_previous_price',
      price_change: 'pp_price_change',
      price_change_date: 'pp_price_change_date',
      status: 'pp_status',
      createdby: 'pp_createdby',
      createddate: 'pp_createddate',
    },
  },
}

exports.Product = Product
