const Production = {
  product_price: {
    tablename: 'product_price',
    prefix: 'pp',
    prefix_: 'pp_',
    selectColums: [
      `pp_product_price_id`,
      `pp_product_id`,
      `pp_description`,
      `pp_barcode`,
      `pp_product_image`,
      `pp_price`,
      `pp_category`,
      `pp_previous_price`,
      `pp_price_change`,
      `pp_price_change_date`,
      `pp_status`,
      `pp_createdby`,
      `pp_createddate`,
    ],
    insertColumns: [
      `product_id`,
      `description`,
      `barcode`,
      `productimage`,
      `price`,
      `category`,
      `previous_price`,
      `price_change`,
      `price_change_date`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      product_price_id: 'pp_product_price_id',
      product_id: 'pp_product_id',
      description: 'pp_description',
      barcode: 'pp_barcode',
      productimage: 'pp_product_image',
      price: 'pp_price',
      category: 'pp_category',
      previous_price: 'pp_previous_price',
      price_change: 'pp_price_change',
      price_change_date: 'pp_price_change_date',
      status: 'pp_status',
      createdby: 'pp_createdby',
      createddate: 'pp_createddate',
    },
  },
  production: {
    tablename: 'production',
    prefix: 'p',
    prefix_: 'p_',
    selectColums: [
      `p_productionid`,
      `p_productid`,
      `p_startdate`,
      `p_enddate`,
      `p_quantityproduced`,
      `p_productionline`,
      `p_supervisorid`,
      `p_notes`,
      `p_status`,
    ],
    insertColumns: [
      `productid`,
      `startdate`,
      `enddate`,
      `quantityproduced`,
      `productionline`,
      `supervisorid`,
      `notes`,
      `status`,
    ],
    selectOptionColumn: {
      productionid: 'p_productionid',
      productid: 'p_productid',
      startdate: 'p_startdate',
      enddate: 'p_enddate',
      quantityproduced: 'p_quantityproduced',
      productionline: 'p_productionline',
      supervisorid: 'p_supervisorid',
      notes: 'p_notes',
      status: 'p_status',
    },
  },
  production_activities: {
    tablename: 'production_activities',
    prefix: 'pa',
    prefix_: 'pa_',
    selectColums: [
      `pa_activityid`,
      `pa_productionid`,
      `pa_activityname`,
      `pa_startdate`,
      `pa_enddate`,
      `pa_workerid`,
    ],
    insertColumns: [
      `activityid`,
      `productionid`,
      `activityname`,
      `startdate`,
      `enddate`,
      `workerid`,
    ],
    selectOptionColumn: {
      activityid: 'pa_activityid',
      productionid: 'pa_productionid',
      activityname: 'pa_activityname',
      startdate: 'pa_startdate',
      enddate: 'pa_enddate',
      workerid: 'pa_workerid',
    },
  },
  production_components: {
    tablename: 'production_components',
    prefix: 'pc',
    prefix_: 'pc_',
    selectColums: [
      `pc_componentid`,
      `pc_productid`,
      `pc_details`,
      `pc_totalcost`,
      `pc_status`,
      `pc_createdby`,
      `pc_createddate`,
    ],
    insertColumns: [`productid`, `details`, `totalcost`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      componentid: 'pc_componentid',
      productid: 'pc_productid',
      details: 'pc_details',
      totalcost: 'pc_totalcost',
      status: 'pc_status',
      createdby: 'pc_createdby',
      createddate: 'pc_createddate',
    },
  },
  production_history: {
    tablename: 'production_history',
    prefix: 'ph',
    prefix_: 'ph_',
    selectColums: [`ph_historyid`, `ph_productionid`, `ph_quantity`, `ph_date`, `ph_status`],
    insertColumns: [`productid`, `quantity`, `date`, `status`],
    selectOptionColumn: {
      historyid: 'ph_historyid',
      productid: 'ph_productionid',
      quantity: 'ph_quantity',
      date: 'ph_date',
      status: 'ph_status',
    },
  },
  production_inventory: {
    tablename: 'production_inventory',
    prefix: 'pi',
    prefix_: 'pi_',
    selectColums: [`pi_inventoryid`, `pi_productid`, `pi_quantity`],
    insertColumns: [`productid`, `quantity`],
    selectOptionColumn: {
      inventoryid: 'pi_inventoryid',
      productid: 'pi_productid',
      quantity: 'pi_quantity',
    },
  },
  production_logs: {
    tablename: 'production_logs',
    prefix: 'pl',
    prefix_: 'pl_',
    selectColums: [`pl_logid`, `pl_description`, `pl_status`, `pl_date`],
    insertColumns: [`description`, `status`, `date`],
    selectOptionColumn: {
      logid: 'pl_logid',
      description: 'pl_description',
      status: 'pl_status',
      date: 'pl_date',
    },
  },
  production_material_count: {
    tablename: 'production_material_count',
    prefix: 'pmc',
    prefix_: 'pmc_',
    selectColums: [
      `pmc_countid`,
      `pmc_productid`,
      `pmc_quantity`,
      `pmc_unit`,
      `pmc_status`,
      `pmc_createdby`,
      `pmc_createddate`,
      `pmc_updateddate`,
    ],
    insertColumns: [
      `productid`,
      `quantity`,
      `unit`,
      `status`,
      `createdby`,
      `createddate`,
      `updateddate`,
    ],
    selectOptionColumn: {
      countid: 'pmc_countid',
      productid: 'pmc_productid',
      quantity: 'pmc_quantity',
      unit: 'pmc_unit',
      status: 'pmc_status',
      createdby: 'pmc_createdby',
      createddate: 'pmc_createddate',
      updateddate: 'pmc_updateddate',
    },
  },
  production_material_history: {
    tablename: 'production_material_history',
    prefix: 'pmh',
    prefix_: 'pmh_',
    selectColums: [
      `pmh_id`,
      `pmh_countId`,
      `pmh_baseQuantity`,
      `pmh_movementUnit`,
      `pmh_baseUnit`,
      `pmh_convertedQuantity`,
      `pmh_movementId`,
      `pmh_type`,
      `pmh_date`,
      `pmh_stocksBefore`,
      `pmh_stocksAfter`,
      `pmh_unitBefore`,
      `pmh_unitAfter`,
    ],
    insertColumns: [
      `countid`,
      `basequantity`,
      `movementunit`,
      `baseunit`,
      `convertedquantity`,
      `movementid`,
      `type`,
      `date`,
      `stocksbefore`,
      `stocksafter`,
      `unitbefore`,
      `unitafter`,
    ],
    selectOptionColumn: {
      id: 'pmh_id',
      countid: 'pmh_countid',
      basequantity: 'pmh_basequantity',
      movementunit: 'pmh_movementunit',
      baseunit: 'pmh_baseunit',
      convertedquantity: 'pmh_convertedquantity',
      movementid: 'pmh_movementid',
      type: 'pmh_type',
      date: 'pmh_date',
      stocksbefore: 'pmh_stocksbefore',
      stocksafter: 'pmh_stocksafter',
      unitbefore: 'pmh_unitbefore',
      unitafter: 'pmh_unitafter',
    },
  },
  production_material_stock_adjustment: {
    tablename: 'production_material_stock_adjustment',
    prefix: 'pmsa',
    prefix_: 'pmsa_',
    selectColums: [`pmsa_id`, `pmsa_date`, `pmsa_note`, `pmsa_content`, `pmsa_status`],
    insertColumns: [`date`, `note`, `content`, `status`],
    selectOptionColumn: {
      id: 'pmsa_id',
      date: 'pmsa_date',
      note: 'pmsa_note',
      content: 'pmsa_content',
      status: 'pmsa_status',
    },
  },
  production_materials: {
    tablename: 'production_materials',
    prefix: 'pm',
    prefix_: 'pm_',
    selectColums: [
      `mpm_productid`,
      `mpm_productname`,
      `mpm_description`,
      `mpm_category`,
      `mpm_vendorid`,
      `mpm_price`,
      `mpm_status`,
      `mpm_createdby`,
      `mpm_createddate`,
    ],
    insertColumns: [
      `productid`,
      `productname`,
      `description`,
      `category`,
      `vendorid`,
      `price`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      productid: 'mpm_productid',
      productname: 'mpm_productname',
      description: 'mpm_description',
      category: 'mpm_category',
      vendorid: 'mpm_vendorid',
      price: 'mpm_price',
      status: 'mpm_status',
      createdby: 'mpm_createdby',
      createddate: 'mpm_createddate',
    },
  },
  production_product_cost: {
    tablename: 'production_product_cost',
    prefix: 'ppc',
    prefix_: 'ppc_',
    selectColums: [
      `ppc_productionid`,
      `ppc_componentid`,
      `ppc_productid`,
      `ppc_cost`,
      `ppc_status`,
      `ppc_createdby`,
      `ppc_createddate`,
    ],
    insertColumns: [
      `productionid`,
      `componentid`,
      `productid`,
      `cost`,
      `status`,
      `createdby`,
      `createddate`,
    ],
    selectOptionColumn: {
      productionid: 'ppc_productionid',
      componentid: 'ppc_componentid',
      productid: 'ppc_productid',
      cost: 'ppc_cost',
      status: 'ppc_status',
      createdby: 'ppc_createdby',
      createddate: 'ppc_createddate',
    },
  },
  production_transfer: {
    tablename: 'production_transfer',
    prefix: 'pt',
    prefix_: 'pt_',
    selectColums: [
      `pt_transferid`,
      `pt_productid`,
      `pt_quantity`,
      `pt_branchid`,
      `pt_status`,
      `pt_createdby`,
      `pt_createddate`,
    ],
    insertColumns: [`productid`, `quantity`, `branchid`, `status`, `createdby`, `createddate`],
    selectOptionColumn: {
      transferid: 'pt_transferid',
      productid: 'pt_productid',
      quantity: 'pt_quantity',
      branchid: 'pt_branchid',
      status: 'pt_status',
      createdby: 'pt_createdby',
      createddate: 'pt_createddate',
    },
  },
}

exports.Production = Production
