const Sales = {
  sales_detail: {
    tablename: 'sales_detail',
    prefix: 'st',
    prefix_: 'st_',
    selectColums: [
      `st_detail_id`,
      `st_date`,
      `st_pos_id`,
      `st_shift`,
      `st_payment_type`,
      `st_description`,
      `st_total`,
      `st_cashier`,
      `st_branch`,
      `st_status`,
    ],
    insertColumns: [
      `date`,
      `pos_id`,
      `shift`,
      `payment_type`,
      `description`,
      `total`,
      `cashier`,
      `branch`,
      `status`,
    ],
    selectOptionColumn: {
      detail_id: 'st_detail_id',
      date: 'st_date',
      pos_id: 'st_pos_id',
      shift: 'st_shift',
      payment_type: 'st_payment_type',
      description: 'st_description',
      total: 'st_total',
      cashier: 'st_cashier',
      branch: 'st_branch',
      status: 'st_status',
    },
  },
  sales_discount: {
    tablename: 'sales_discount',
    prefix: 'sd',
    prefix_: 'sd_',
    selectColums: [`sd_id`, `sd_detailid`, `sd_discountid`, `sd_customerinfo`, `sd_amount`],
  },
  sales_inventory_history: {
    tablename: 'sales_inventory_history',
    prefix: 'sih',
    prefix_: 'sih_',
    selectColums: [
      `sih_historyid`,
      `sih_detailid`,
      `sih_date`,
      `sih_productid`,
      `sih_branch`,
      `sih_quantity`,
    ],
    insertColumns: [`detailid`, `date`, `productid`, `branch`, `quantity`],
    selectOptionColumn: {
      historyid: 'sih_historyid',
      detailid: 'sih_detailid',
      date: 'sih_date',
      productid: 'sih_productid',
      branch: 'sih_branch',
      quantity: 'sih_quantity',
    },
  },
  sales_item: {
    tablename: 'sales_item',
    prefix: 'si',
    prefix_: 'si_',
    selectColums: [`si_detail_id`, `si_date`, `si_item`, `si_price`, `si_quantity`, `si_total`],
    insertColumns: [`detail_id`, `date`, `item`, `price`, `quantity`, `total`],
    selectOptionColumn: {
      detail_id: 'si_detail_id',
      date: 'si_date',
      item: 'si_item',
      price: 'si_price',
      quantity: 'si_quantity',
      total: 'si_total',
    },
  },
  sales_promo: {
    tablename: 'sales_promo',
    prefix: 'sp',
    prefix_: 'sp_',
    selectColums: [`sp_id`, `sp_promoid`, `sp_detailid`],
    insertColumns: [`promoid`, `detailid`],
    selectOptionColumn: {
      id: 'sp_id',
      promoid: 'sp_promoid',
      detailid: 'sp_detailid',
    },
  },
}

exports.Sales = Sales
