const Stock = {
  stock_adjustment: {
    tablename: 'stock_adjustment',
    prefix: 'sa',
    prefix_: 'sa_',
    selectColums: [
      `sa_adjustmentid`,
      `sa_productid`,
      `sa_adjustmentdate`,
      `sa_adjustmenttype`,
      `sa_quantityadjusted`,
      `sa_reason`,
      `sa_adjustedby`,
      `sa_notes`,
    ],
    insertColumns: [
      `adjustmentid`,
      `productid`,
      `adjustmentdate`,
      `adjustmenttype`,
      `quantityadjusted`,
      `reason`,
      `adjustedby`,
      `notes`,
    ],
    selectOptionColumn: {
      adjustmentid: 'sa_adjustmentid',
      productid: 'sa_productid',
      adjustmentdate: 'sa_adjustmentdate',
      adjustmenttype: 'sa_adjustmenttype',
      quantityadjusted: 'sa_quantityadjusted',
      reason: 'sa_reason',
      adjustedby: 'sa_adjustedby',
      notes: 'sa_notes',
    },
  },
  stock_adjustment_detail: {
    tablename: 'stock_adjustment_detail',
    prefix: 'sad',
    prefix_: 'sad_',
    selectColums: [
      `sad_id`,
      `sad_branchid`,
      `sad_details`,
      `sad_reason`,
      `sad_createddate`,
      `sad_createdby`,
      `sad_notes`,
      `sad_status`,
      `sad_attachments`,
    ],
    insertColumns: [
      `branchid`,
      `details`,
      `reason`,
      `createddate`,
      `createdby`,
      `notes`,
      `status`,
      `attachments`,
    ],
    selectOptionColumn: {
      id: 'sad_id',
      branchid: 'sad_branchid',
      details: 'sad_details',
      reason: 'sad_reason',
      createddate: 'sad_createddate',
      createdby: 'sad_createdby',
      notes: 'sad_notes',
      status: 'sad_status',
      attachments: 'sad_attachments',
    },
  },
  stock_adjustment_item: {
    tablename: 'stock_adjustment_item',
    prefix: 'sai',
    prefix_: 'sai_',
    selectColums: [`sai_id`, `sai_detailid`, `sai_productid`, `sai_quantity`, `sai_stockafter`],
    insertColumns: [`detailid`, `productid`, `quantity`, `stockafter`],
    selectOptionColumn: {
      id: 'sai_id',
      detailid: 'sai_detailid',
      productid: 'sai_productid',
      quantity: 'sai_quantity',
      stockafter: 'sai_stockafter',
    },
  },
}
